### PR TITLE
allow plated holes to be either horizontal or vertical

### PR DESCRIPTION
**Pull request by ShiboSoftwareDev**
+ biome format
/claim #43

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
it's a bit hard to pick apart the changes because of the mixed formatting, can we `@tscircuit/plop` biome.json to keep it consistent? There's so many changes

**Comment by ShiboSoftwareDev** [comment]
@seveibar I added the file but bun format has no effect

**Review by seveibar — APPROVED** [review]
AWESOME

**Comment by seveibar** [comment]
@ShiboSoftwareDev you might need to add a script "format": "biome format --write ."

**Comment by seveibar** [comment]
@biomejs/biome is the package name

**Pull request merged**
