### PR TITLE
updating jscad-electronics to fix cap footprints not changing the 3d capacitor color in snippets

### PR DESCRIPTION
**Pull request by Abse2001**

### CODE REVIEW

**Review by imrishabh18 — COMMENTED** [review]
Can you please yalc this version of `jscad-electronics` and run the 3d viewer to confirm that things are not breaking? The last time some of the dependencies were updated, it broke the view in snippets

**Comment by Abse2001** [comment]
@imrishabh18 
image

**Comment by Abse2001** [comment]
@imrishabh18 is this what you wanted?

**Comment by imrishabh18** [comment]
Yeah, just wanted to make sure. That the snippets 3d-viewer is fine, and nothing broke

**Comment by Abse2001** [comment]
Ok, can I get an approve? @imrishabh18

**Pull request merged**
